import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { SiteHeader } from "@/components/site-header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#0B3A4A",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="bg-[#0B3A4A]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-[100dvh] overflow-x-hidden bg-[#0B3A4A] font-sans text-slate-900 antialiased`}
      >
        <div
          aria-hidden="true"
          className="pointer-events-none fixed inset-0 overflow-hidden"
        >
          <Image
            src="/esports-bg.avif"
            alt=""
            fill
            unoptimized={true}
            priority
            sizes="100vw"
            className="object-cover object-[75%_center] md:object-center"
          />
        </div>

        <div className="relative z-0 min-h-[100dvh]">
          <SiteHeader />
          {children}
        </div>
        <SpeedInsights />
      </body>
    </html>
  );
}
